services:
  php:
    image: rugolinifr/enhanced-find-by:1.1.0
    build:
      context: $PWD
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    networks:
      - enhanced_find_by

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: find_by
    ports:
      - "14336:3306"
    volumes:
      - $PWD/.local/mysql:/var/lib/mysql
    networks:
      - enhanced_find_by

networks:
  enhanced_find_by:
    driver: bridge